_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 14d344cf-05c6-4803-87b9-458640a2ddc8
name: terminus-build-tools-d9test2
mail: mostafizur.rahman@pantheon.io
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
